**动态内存申请指针判空问题**

**malloc失败与new失败差异**

- malloc失败，返回空指针
- new失败，在最新的C++11中，会抛出异常



**malloc失败处理方式**

对返回的指针进行判空



**new失败处理方式**

- 方式1：new申请内存后，对返回的指针使用不判空，new失败程序会抛出异常并退出
- 方式2：使用try catch捕获异常，并做相应处理，程序继续运行，或使用std::nothrow，不抛出异常，对指针的使用需判空
- 方式3：使用set_new_handle指定new失败的处理接口。在接口内可做释放多余内存以满足new的需要，或在接口内调用exit退出程序



**malloc失败处理**

```c++
#include <iostream>
#include <exception>
#include <new>

#define MAX_NUM (375000000)

int main()
{
    char *p_c = (char *)malloc(MAX_NUM * 4);
    if (p_c == NULL) {
        std::cout << "malloc failed" << std::endl;
    } else {
        free(p_c);
        p_c = NULL;
        std::cout << "malloc succeed" << std::endl;
    }
}
```



**new失败处理方式2**

```c++
#include <iostream>
#include <exception>
#include <new>

#define MAX_NUM (375000000)

int main()
{
    int *p_cpp = nullptr;

    try {
        p_cpp = new int[MAX_NUM];
    }
    catch (std::exception &e){
        std::cout << e.what() << std::endl;
    }
    if (p_cpp == nullptr) {
        //....
    }

    system("pause");
    return 0;
}

//
int main()
{
    int *p_cpp = nullptr;
    
    p_cpp = new (std::nothrow)int[MAX_NUM];
    if (p_cpp == nullptr) {
        std::cout << "new error with no throw" << std::endl;
    }
     
    system("pause");
    return 0;
}
```



**new失败处理方式3**

```c++
#include <iostream>
#include <exception>
#include <new>

#define MAX_NUM (375000000)

void handle_new_error()
{
    std::cout << "new error" << std::endl;
    exit(0);
}

int main()
{
    int *p_cpp = nullptr;

    std::set_new_handler(handle_new_error);
    p_cpp = new int[MAX_NUM];
	if (p_cpp == nullptr) {
        //......     
    }
    
    system("pause");
    return 0;
}

```